/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelloIndexRouteImport } from './routes/hello/index'
import { Route as PostPostIdRouteImport } from './routes/post/$postId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelloIndexRoute = HelloIndexRouteImport.update({
  id: '/hello/',
  path: '/hello/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/post/$postId': typeof PostPostIdRoute
  '/hello': typeof HelloIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/post/$postId': typeof PostPostIdRoute
  '/hello': typeof HelloIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/post/$postId': typeof PostPostIdRoute
  '/hello/': typeof HelloIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/post/$postId' | '/hello'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/post/$postId' | '/hello'
  id: '__root__' | '/' | '/post/$postId' | '/hello/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostPostIdRoute: typeof PostPostIdRoute
  HelloIndexRoute: typeof HelloIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hello/': {
      id: '/hello/'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof HelloIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostPostIdRoute: PostPostIdRoute,
  HelloIndexRoute: HelloIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
